name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/workflow-build.yaml
    secrets: inherit
